# Generated by Django 3.0.6 on 2020-05-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0003_userconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
